/**
 * Endpoints of the PokéAPI
 */
export const ENDPOINTS = {
  BERRY: '/berry',
  BERRY_FIRMNESS: '/berry-firmness',
  BERRY_FLAVOR: '/berry-flavor',
  CONTEST_EFFECT: '/contest-effect',
  CONTEST_TYPE: '/contest-type',
  ENCOUNTER_CONDITION: '/encounter-condition',
  ENCOUNTER_CONDITION_VALUE: '/encounter-condition-value',
  ENCOUNTER_METHOD: '/encounter-method',
  EVOLUTION_CHAIN: '/evolution-chain',
  EVOLUTION_TRIGGER: '/evolution-trigger',
  GENERATION: '/generation',
  ITEM: '/item',
  ITEM_ATTRIBUTE: '/item-attribute',
  ITEM_CATEGORY: '/item-category',
  ITEM_FLING_EFFECT: '/item-fling-effect',
  SUPER_CONTEST_EFFECT: '/super-contest-effect',
  ITEM_POCKET: '/item-pocket',
  LOCATION: '/location',
  LOCATION_AREA: '/location-area',
  MACHINE: '/machine',
  POKEDEX: '/pokedex',
  MOVE: '/move',
  VERSION: '/version',
  ABILITY: '/ability',
  VERSION_GROUP: '/version-group',
  CHARACTERISTIC: '/characteristic',
  EGG_GROUP: '/egg-group',
  MOVE_AILMENT: '/move-ailment',
  GENDER: '/gender',
  MOVE_BATTLE_STYLE: '/move-battle-style',
  GROWTH_RATE: '/growth-rate',
  PALPARK_AREA: '/pal-park-area',
  MOVE_CATEGORY: '/move-category',
  REGION: '/region',
  MOVE_DAMAGE_CLASS: '/move-damage-class',
  MOVE_LEARN_METHOD: '/move-learn-method',
  MOVE_TARGET: '/move-target',
  NATURE: '/nature',
  LANGUAGE: '/language',
  POKEATHLON_STAT: '/pokeathlon-stat',
  POKEMON: '/pokemon',
  POKEMON_COLOR: '/pokemon-color',
  POKEMON_FORM: '/pokemon-form',
  POKEMON_HABITAT: '/pokemon-habitat',
  POKEMON_LOCATION_AREA: '/pokemon/:id/encounters',
  POKEMON_SHAPE: '/pokemon-shape',
  POKEMON_SPECIES: '/pokemon-species',
  STAT: '/stat',
  TYPE: '/type',
} as const
