export const EVOLUTION_TRIGGERS = {
  LEVEL_UP: 1,
  OTHER: 10,
  SHED: 4,
  SPIN: 5,
  TAKE_DAMAGE: 9,
  THREE_CRITICAL_HITS: 8,
  TOWER_OF_DARKNESS: 6,
  TOWER_OF_WATER: 7,
  TRADE: 2,
  USE_ITEM: 3,
} as const
